### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Gariney** [webgeodatavore/azimuth_measurement#5]
When I try to activiate Azimuth Measurement I get the followoing error message

Couldn't load plugin 'AzimuthMeasurement' due to an error when calling its classFactory() method 

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Irvine/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AzimuthMeasurement\__init__.py", line 35, in classFactory
    return AzimuthMeasurement(iface)
  File "C:/Users/Irvine/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AzimuthMeasurement\azimuth_measurement.py", line 88, in __init__
    self.draw_mono_line = DrawMonoLineMapTool(self.canvas)
  File "C:/Users/Irvine/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AzimuthMeasurement\draw_mono_line_map_tool.py", line 17, in __init__
    int(s.value('default_measure_color_red')),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.6.0-Noosa Noosa, 58734527ab 

Python Path:
C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python
C:/Users/Irvine/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Irvine/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.6\bin\python37.zip
C:\PROGRA~1\QGIS3~1.6\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib
C:\Program Files\QGIS 3.6\bin
C:\PROGRA~1\QGIS3~1.6\apps\Python37
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Irvine/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Irvine/Documents/QGIS/RSC

**Comment by ThomasG77** [comment]
Related to #3. I've made an update but I'm waiting plugin upgrade approval from QGIS project.
When at page https://plugins.qgis.org/plugins/AzimuthMeasurement/, it will show "version 0.2.1" (not a the moment, don't know when), you can try to reinstall/upgrade the plugin.
Then, please, make a feedback here if it works after my change.

Thanks

**Comment by ThomasG77** [comment]
No feedback since a month => close. Feel free to reopen if not solved
